# Site settings
title: Adrian Lam - Data Scientist
email: ayplam@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "ayplam.github.io" # the base hostname & protocol for your site
highlighter: rouge
# Build settings
gems: [jekyll-paginate]
permalink: pretty
include: ['_pages']

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed